name: sneakerbot

env_file:
  - .env

services:
  appserver:
    type: compose
    run_as_root:
      - chmod +x ./container_start.sh
    build:
      - npm install
    services:
      image: samc621/sneakerbot
      command: dumb-init --
      ports:
        - '8000:8000'
        - '5900:5900'
      environment:
        NODE_ENV: lando

  database:
    type: postgres:13
    portforward: true
    creds:
      database: sneakerbot

events:
  post-start:
    - appserver: npm install
    - appserver: npx knex migrate:latest
    - appserver: npx knex seed:run

tooling:
  npm:
    service: appserver
  npx:
    service: appserver
  node:
    service: appserver
